str = 'skdaskerkjsalkj'
count = str.count('s')
count1 = str.count('k')
count2= str.count('d')
count3 = str.count('a')
count4 = str.count('e')
count5 = str.count('j')
count6 = str.count('l')
count7 = str.count('r')
print(f"该字母出现的次数为{count}")
print(f"该字母出现的次数为{count1}")
print(f"该字母出现的次数为{count2}")
print(f"该字母出现的次数为{count3}")
print(f"该字母出现的次数为{count4}")
print(f"该字母出现的次数为{count5}")
print(f"该字母出现的次数为{count6}")
print(f"该字母出现的次数为{count7}")
