f = open("C:/pyfile/邀请函.txt", "a", encoding="UTF-8")
f.write("\nbest regards\n李雷")
f = open("C:/pyfile/丁一的邀请函.txt", "w", encoding="UTF-8")
f.write("丁一:\n诚挚邀请您来参加本次宴会\nbest regards\n李雷")
f = open("C:/pyfile/韩梅梅的邀请函.txt", "w", encoding="UTF-8")
f.write("韩梅梅:\n诚挚邀请您来参加本次宴会\nbest regards\n李雷")
f = open("C:/pyfile/王美丽的邀请函.txt", "w", encoding="UTF-8")
f.write("王美丽:\n诚挚邀请您来参加本次宴会\nbest regards\n李雷")
f.close()